### ISSUE TITLE
dumpWebGLTextureData() is undefined

### ISSUE THREAD

**Issue by WillCotzeeAlt** [krapnikkk/SketchfabTextureDump#3]
When I run "dumpWebGLTextureData()" in chrome's console, it returns "undefined" and nothing happens... I got it to work once, but I have no idea how I did it. What does "undefined" mean and how can I fix it?

**Comment by beetaa** [comment]
+1

**Comment by krapnikkk** [comment]
open the model view url & run the user script;
model view link template：sketchfab.com/models/**[model id here!]**/embed?autostart=1
for example:
https://sketchfab.com/3d-models/fox-isoroom-concept-by-yoshi-yoshitani-0966c3d062f243eda5f52516f9919480
this model id is:
0966c3d062f243eda5f52516f9919480
this model view link is:
https://sketchfab.com/models/0966c3d062f243eda5f52516f9919480/embed?autostart=1

**Comment by beetaa** [comment]
> 

cool, all things done! thank you. 👍
