### ISSUE TITLE
Uncaught TypeError: newWin is null

### ISSUE THREAD

**Issue by miccall** [krapnikkk/SketchfabTextureDump#4]
Uncaught TypeError: newWin is null
    downFile moz-extension://781817be-8dda-405b-880f-4dde7bcaf77e/userscripts/SketchfabTextureDump.user.js?id=b014a716-9431-4e73-b642-101bc70a930e:147
    readWebTextureData moz-extension://781817be-8dda-405b-880f-4dde7bcaf77e/userscripts/SketchfabTextureDump.user.js?id=b014a716-9431-4e73-b642-101bc70a930e:117
    dumpWebGLTextureData moz-extension://781817be-8dda-405b-880f-4dde7bcaf77e/userscripts/SketchfabTextureDump.user.js?id=b014a716-9431-4e73-b642-101bc70a930e:137
    <anonymous> debugger eval code:1
debugger eval code:147:5
    downFile moz-extension://781817be-8dda-405b-880f-4dde7bcaf77e/userscripts/SketchfabTextureDump.user.js?id=b014a716-9431-4e73-b642-101bc70a930e:147
    readWebTextureData moz-extension://781817be-8dda-405b-880f-4dde7bcaf77e/userscripts/SketchfabTextureDump.user.js?id=b014a716-9431-4e73-b642-101bc70a930e:117
    dumpWebGLTextureData moz-extension://781817be-8dda-405b-880f-4dde7bcaf77e/userscripts/SketchfabTextureDump.user.js?id=b014a716-9431-4e73-b642-101bc70a930e:137
    <anonymous> debugger eval code:1

**Comment by krapnikkk** [comment]
firefox？

**Comment by krapnikkk** [comment]
允许firefox弹出窗口即可

**Comment by miccall** [comment]
> 弹出

搞定了

**Comment by miccall** [comment]
简单说一下吧，就不想提pr了
重写了一下 download 方法
```
    downLoadByLink = (url, filename) =>{
        //  filename 需要包含扩展名
        var link,
            evt;
        link = document.createElement('a');
        link.href = url;
        filename && link.setAttribute('download', filename);
        if(document.fireEvent) {
            window.open(link.href);
        }else {
            evt = document.createEvent('MouseEvents');
            evt.initEvent('click', true, true);
            link.dispatchEvent(evt);
        }
    };
```

```
调用
downLoadByLink(canvas.toDataURL(),`${Date.now()}.png`);
```

**Comment by krapnikkk** [comment]
thanks
