### ISSUE TITLE
只能下载到一个 阴影贴图

### ISSUE THREAD

**Issue by pendave** [krapnikkk/SketchfabTextureDump#5]
为啥这个 https://sketchfab.com/models/faef9fe5ace445e7b2989d1c1ece361c/embed?autostart=1 只能下载到一个 阴影贴图？
![1667720195521](https://user-images.githubusercontent.com/1331881/200159602-823f811e-de3a-4437-9321-efbd42ea849a.png)

**Comment by krapnikkk** [comment]
抽空更新了一下，使用最新版即可解决这个问题

**Comment by pendave** [comment]
大佬太牛叉了。膜拜 Orz
这个论坛里讨论的手动截取解密后的 file.osgjs 也能用油猴脚本实现吗？不知道还有没有用
https://groinkick.freeforums.net/thread/49/ripping-sketchfab-models?page=2

**Comment by krapnikkk** [comment]
正在施工中~

**Comment by pendave** [comment]
下载  file.osgjs 的代码如下，这些简单的 js 代码我还能懂，大佬你写的油猴脚本我也只能看懂一小部分。请问大佬应该看什么样的 js 教程来实现看懂你的脚本的水平啊？┗(•ω•;)┛
还有，Python 脚本配合 Blender 转化出 3D 模型您也可以用油猴脚本实现吗？
`let downloadBlob, downloadURL;

downloadBlob = function(data, fileName, mimeType) {
  let blob, url;
  blob = new Blob([data], {
    type: mimeType
  });
  url = window.URL.createObjectURL(blob);
  downloadURL(url, fileName);
  setTimeout(function() {
    return window.URL.revokeObjectURL(url);
  }, 1000);
};

downloadURL = function(data, fileName) {
  let a;
  a = document.createElement('a');
  a.href = data;
  a.download = fileName;
  document.body.appendChild(a);
  a.style = 'display: none';
  a.click();
  a.remove();
};

downloadBlob(i, 'file.osgjs', 'application/octet-stream');`

**Comment by krapnikkk** [comment]
- 纹理导出原理 
see：https://zhuanlan.zhihu.com/p/571651565
- 看什么样的 js 教程来实现看懂你的脚本的
js仅仅只是工具，需要补全更多的是计算机图形学相关的知识，不过上面的教程原理解释的七七八八了
- Python 脚本配合 Blender 转化出 3D 模型您也可以用油猴脚本实现吗
```
任何可以用 JavaScript 来写的应用，最终都将用 JavaScript 来写。
```
