### ISSUE TITLE
[BUG]执行dumpWebGLTextureData()函数出错

### ISSUE THREAD

**Issue by lushangkan** [krapnikkk/SketchfabTextureDump#6]
**错误出现模型:** https://sketchfab.com/models/281eedf29dbf4293b7113cd6d89a01ff/embed?autostart=1

**错误触发步骤:** 

1. 在模型加载完成时调用dumpWebGLTextureData()函数

**错误日志:** 

```
【dump texture:0/1】oops~something went wrong,u can refresh the page & try again
undefined
```

**Comment by krapnikkk** [comment]
把首行代码中的256调整为128即可
