### ISSUE TITLE
某些模型页面无法正常加载（不知道大佬现在还接不接受反馈~

### ISSUE THREAD

**Issue by Sostay** [krapnikkk/SketchfabTextureDump#7]
目前V2版本在大部分页面正常工作（但是贴图貌似是垂直翻转的，我用的是一个基于你的修改版本），但是目前发现在部分页面会导致模型无法正常加载，所以也下载不了贴图。下面是我发现的部分无法正常加载的页面——
https://sketchfab.com/models/c8a964f384ed457ba0801d6cfe536d6d/embed?autostart=1&internal=1&tracking=0&ui_ar=0&ui_infos=0&ui_snapshots=1&ui_stop=0&ui_theatre=1&ui_watermark=0
https://sketchfab.com/models/3e139bcf57124aa7a07a0ee4d5631755/embed?autostart=1&internal=1&tracking=0&ui_ar=0&ui_infos=0&ui_snapshots=1&ui_stop=0&ui_theatre=1&ui_watermark=0
https://sketchfab.com/models/0faa4ccde79d40c38a41f7706d34c0a3/embed?autostart=1&internal=1&tracking=0&ui_ar=0&ui_infos=0&ui_snapshots=1&ui_stop=0&ui_theatre=1&ui_watermark=0
https://sketchfab.com/models/ed2322742e2244ac8d00285f0ec46a62/embed?autostart=1&internal=1&tracking=0&ui_ar=0&ui_infos=0&ui_snapshots=1&ui_stop=0&ui_theatre=1&ui_watermark=0

**Comment by krapnikkk** [comment]
1.贴图颠倒是feature,see：UNPACK_FLIP_Y_WEBGL
2.这些模型有空再看看，如果急的话我这边可以直接帮你提取

**Comment by Sostay** [comment]
> 1.贴图颠倒是feature,see：UNPACK_FLIP_Y_WEBGL 2.这些模型有空再看看，如果急的话我这边可以直接帮你提取

不急不急 感谢回复！我这边偶尔也用Spector.js抓一些贴图的

**Comment by krapnikkk** [comment]
总有人跟我说之前写的脚本过期了，趁着中秋节写了个网页，傻瓜式一键下载加密纹理，enjoy it~
https://sf-texture-decode.vercel.app/
